"""add_og_image_to_stem2

Revision ID: 00d871d2ed25
Revises: dcdcd9230de6
Create Date: 2025-03-06 14:55:27.599866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d871d2ed25'
down_revision: Union[str, None] = 'dcdcd9230de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stems', sa.Column('ogp_image_obj_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stems', 'ogp_image_obj_key')
    # ### end Alembic commands ###
