"""add_can_width_to_stem

Revision ID: 134dd499544f
Revises: 00d871d2ed25
Create Date: 2025-03-07 11:01:05.237810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134dd499544f'
down_revision: Union[str, None] = '00d871d2ed25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stems', sa.Column('can_width_mm', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stems', 'can_width_mm')
    # ### end Alembic commands ###
