"""add_debug_image_obj

Revision ID: 135808efe71d
Revises: cd6ef891e0b3
Create Date: 2025-03-04 02:52:12.966690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135808efe71d'
down_revision: Union[str, None] = 'cd6ef891e0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entire_trees', sa.Column('debug_image_obj_key', sa.String(length=255), nullable=True))
    op.add_column('stem_holes', sa.Column('debug_image_obj_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stem_holes', 'debug_image_obj_key')
    op.drop_column('entire_trees', 'debug_image_obj_key')
    # ### end Alembic commands ###
