"""empty message

Revision ID: 15b0bf08dfe1
Revises: 2e76adde6a8c
Create Date: 2025-02-17 12:08:01.714398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b0bf08dfe1'
down_revision: Union[str, None] = '2e76adde6a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipality_stats', sa.Column('kobu_count', sa.Integer(), nullable=False))
    op.add_column('prefecture_stats', sa.Column('kobu_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prefecture_stats', 'kobu_count')
    op.drop_column('municipality_stats', 'kobu_count')
    # ### end Alembic commands ###
