"""add_real_age_to_stem

Revision ID: 18c1a25a83e7
Revises: 1be5b1f86243
Create Date: 2025-03-04 04:09:20.141998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c1a25a83e7'
down_revision: Union[str, None] = '1be5b1f86243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stems', sa.Column('texture_real', sa.Float(), nullable=True))
    op.add_column('stems', sa.Column('age_texture', sa.Integer(), nullable=True))
    op.add_column('stems', sa.Column('age_circumfence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stems', 'age_circumfence')
    op.drop_column('stems', 'age_texture')
    op.drop_column('stems', 'texture_real')
    # ### end Alembic commands ###
