"""add_debug_image_to_stem

Revision ID: 1be5b1f86243
Revises: 4c984ef6c8b7
Create Date: 2025-03-04 03:12:54.449480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be5b1f86243'
down_revision: Union[str, None] = '4c984ef6c8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stems', sa.Column('debug_image_obj_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stems', 'debug_image_obj_key')
    # ### end Alembic commands ###
