"""bloom refactor

Revision ID: 391f64086038
Revises: faa83b6c8a0b
Create Date: 2025-03-04 13:32:26.480061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391f64086038'
down_revision: Union[str, None] = 'faa83b6c8a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entire_trees', sa.Column('vitality_noleaf', sa.Integer(), nullable=True))
    op.add_column('entire_trees', sa.Column('vitality_noleaf_real', sa.Float(), nullable=True))
    op.add_column('entire_trees', sa.Column('vitality_noleaf_weight', sa.Float(), nullable=True))
    op.add_column('entire_trees', sa.Column('vitality_bloom', sa.Integer(), nullable=True))
    op.add_column('entire_trees', sa.Column('vitality_bloom_real', sa.Float(), nullable=True))
    op.add_column('entire_trees', sa.Column('vitality_bloom_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entire_trees', 'vitality_bloom_weight')
    op.drop_column('entire_trees', 'vitality_bloom_real')
    op.drop_column('entire_trees', 'vitality_bloom')
    op.drop_column('entire_trees', 'vitality_noleaf_weight')
    op.drop_column('entire_trees', 'vitality_noleaf_real')
    op.drop_column('entire_trees', 'vitality_noleaf')
    # ### end Alembic commands ###
