"""add_debug_image_obj2

Revision ID: 4c984ef6c8b7
Revises: 135808efe71d
Create Date: 2025-03-04 02:52:48.299691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c984ef6c8b7'
down_revision: Union[str, None] = '135808efe71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entire_trees', sa.Column('debug_image_obj2_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entire_trees', 'debug_image_obj2_key')
    # ### end Alembic commands ###
