"""initial

Revision ID: 57e0ef4ea2d1
Revises: 
Create Date: 2025-02-27 11:09:26.534301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '57e0ef4ea2d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('municipality_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('municipality_code', sa.String(length=8), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('position', Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('total_trees', sa.Integer(), nullable=False),
    sa.Column('vitality1_count', sa.Integer(), nullable=False),
    sa.Column('vitality2_count', sa.Integer(), nullable=False),
    sa.Column('vitality3_count', sa.Integer(), nullable=False),
    sa.Column('vitality4_count', sa.Integer(), nullable=False),
    sa.Column('vitality5_count', sa.Integer(), nullable=False),
    sa.Column('age20_count', sa.Integer(), nullable=False),
    sa.Column('age30_count', sa.Integer(), nullable=False),
    sa.Column('age40_count', sa.Integer(), nullable=False),
    sa.Column('age50_count', sa.Integer(), nullable=False),
    sa.Column('age60_count', sa.Integer(), nullable=False),
    sa.Column('hole_count', sa.Integer(), nullable=False),
    sa.Column('tengus_count', sa.Integer(), nullable=False),
    sa.Column('mushroom_count', sa.Integer(), nullable=False),
    sa.Column('kobu_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_municipality_stats_position', 'municipality_stats', ['position'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_municipality_stats_municipality_code'), 'municipality_stats', ['municipality_code'], unique=False)
    op.create_geospatial_table('prefecture_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefecture_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('position', Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('total_trees', sa.Integer(), nullable=False),
    sa.Column('vitality1_count', sa.Integer(), nullable=False),
    sa.Column('vitality2_count', sa.Integer(), nullable=False),
    sa.Column('vitality3_count', sa.Integer(), nullable=False),
    sa.Column('vitality4_count', sa.Integer(), nullable=False),
    sa.Column('vitality5_count', sa.Integer(), nullable=False),
    sa.Column('age20_count', sa.Integer(), nullable=False),
    sa.Column('age30_count', sa.Integer(), nullable=False),
    sa.Column('age40_count', sa.Integer(), nullable=False),
    sa.Column('age50_count', sa.Integer(), nullable=False),
    sa.Column('age60_count', sa.Integer(), nullable=False),
    sa.Column('hole_count', sa.Integer(), nullable=False),
    sa.Column('tengus_count', sa.Integer(), nullable=False),
    sa.Column('mushroom_count', sa.Integer(), nullable=False),
    sa.Column('kobu_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefecture_code')
    )
    op.create_geospatial_index('idx_prefecture_stats_position', 'prefecture_stats', ['position'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('ip_addr', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_geospatial_table('trees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contributor', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('position', Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('prefecture_code', sa.String(length=2), nullable=True),
    sa.Column('municipality_code', sa.String(length=8), nullable=True),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_geospatial_index('idx_trees_position', 'trees', ['position'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trees_censorship_status'), 'trees', ['censorship_status'], unique=False)
    op.create_index(op.f('ix_trees_created_at'), 'trees', ['created_at'], unique=False)
    op.create_index(op.f('ix_trees_municipality_code'), 'trees', ['municipality_code'], unique=False)
    op.create_index(op.f('ix_trees_prefecture_code'), 'trees', ['prefecture_code'], unique=False)
    op.create_table('entire_trees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('vitality', sa.Integer(), nullable=True),
    sa.Column('vitality_real', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('decorated_image_obj_key', sa.String(length=255), nullable=True),
    sa.Column('ogp_image_obj_key', sa.String(length=255), nullable=True),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_entire_trees_censorship_status'), 'entire_trees', ['censorship_status'], unique=False)
    op.create_index(op.f('ix_entire_trees_vitality'), 'entire_trees', ['vitality'], unique=False)
    op.create_table('kobus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_kobus_censorship_status'), 'kobus', ['censorship_status'], unique=False)
    op.create_table('mushrooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_mushrooms_censorship_status'), 'mushrooms', ['censorship_status'], unique=False)
    op.create_table('stem_holes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_stem_holes_censorship_status'), 'stem_holes', ['censorship_status'], unique=False)
    op.create_table('stems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('can_detected', sa.Boolean(), nullable=False),
    sa.Column('circumference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('texture', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_stems_age'), 'stems', ['age'], unique=False)
    op.create_index(op.f('ix_stems_censorship_status'), 'stems', ['censorship_status'], unique=False)
    op.create_table('tengus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_tengus_censorship_status'), 'tengus', ['censorship_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tengus_censorship_status'), table_name='tengus')
    op.drop_table('tengus')
    op.drop_index(op.f('ix_stems_censorship_status'), table_name='stems')
    op.drop_index(op.f('ix_stems_age'), table_name='stems')
    op.drop_table('stems')
    op.drop_index(op.f('ix_stem_holes_censorship_status'), table_name='stem_holes')
    op.drop_table('stem_holes')
    op.drop_index(op.f('ix_mushrooms_censorship_status'), table_name='mushrooms')
    op.drop_table('mushrooms')
    op.drop_index(op.f('ix_kobus_censorship_status'), table_name='kobus')
    op.drop_table('kobus')
    op.drop_index(op.f('ix_entire_trees_vitality'), table_name='entire_trees')
    op.drop_index(op.f('ix_entire_trees_censorship_status'), table_name='entire_trees')
    op.drop_table('entire_trees')
    op.drop_index(op.f('ix_trees_prefecture_code'), table_name='trees')
    op.drop_index(op.f('ix_trees_municipality_code'), table_name='trees')
    op.drop_index(op.f('ix_trees_created_at'), table_name='trees')
    op.drop_index(op.f('ix_trees_censorship_status'), table_name='trees')
    op.drop_geospatial_index('idx_trees_position', table_name='trees', postgresql_using='gist', column_name='position')
    op.drop_geospatial_table('trees')
    op.drop_table('users')
    op.drop_geospatial_index('idx_prefecture_stats_position', table_name='prefecture_stats', postgresql_using='gist', column_name='position')
    op.drop_geospatial_table('prefecture_stats')
    op.drop_index(op.f('ix_municipality_stats_municipality_code'), table_name='municipality_stats')
    op.drop_geospatial_index('idx_municipality_stats_position', table_name='municipality_stats', postgresql_using='gist', column_name='position')
    op.drop_geospatial_table('municipality_stats')
    # ### end Alembic commands ###
