"""initial

Revision ID: ab96617ee550
Revises: 
Create Date: 2025-02-03 11:56:56.734398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'ab96617ee550'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('ip_addr', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_geospatial_table('trees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contributor', sa.String(length=100), nullable=True),
    sa.Column('vitality', sa.Integer(), nullable=True),
    sa.Column('vitality_real', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('position', Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('prefecture_code', sa.String(length=2), nullable=True),
    sa.Column('municipality_code', sa.String(length=8), nullable=True),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('decorated_image_obj_key', sa.String(length=255), nullable=True),
    sa.Column('ogp_image_obj_key', sa.String(length=255), nullable=True),
    sa.Column('censorship_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_geospatial_index('idx_trees_position', 'trees', ['position'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trees_censorship_status'), 'trees', ['censorship_status'], unique=False)
    op.create_index(op.f('ix_trees_created_at'), 'trees', ['created_at'], unique=False)
    op.create_index(op.f('ix_trees_municipality_code'), 'trees', ['municipality_code'], unique=False)
    op.create_index(op.f('ix_trees_prefecture_code'), 'trees', ['prefecture_code'], unique=False)
    op.create_table('mushrooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('stem_holes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('stems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('can_detected', sa.Boolean(), nullable=False),
    sa.Column('circumference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('texture', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('tengus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_obj_key', sa.String(length=255), nullable=False),
    sa.Column('thumb_obj_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tengus')
    op.drop_table('stems')
    op.drop_table('stem_holes')
    op.drop_table('mushrooms')
    op.drop_index(op.f('ix_trees_prefecture_code'), table_name='trees')
    op.drop_index(op.f('ix_trees_municipality_code'), table_name='trees')
    op.drop_index(op.f('ix_trees_created_at'), table_name='trees')
    op.drop_index(op.f('ix_trees_censorship_status'), table_name='trees')
    op.drop_geospatial_index('idx_trees_position', table_name='trees', postgresql_using='gist', column_name='position')
    op.drop_geospatial_table('trees')
    op.drop_table('users')
    # ### end Alembic commands ###
