"""add_real_age_to_stem2

Revision ID: ade5141bc3a7
Revises: 18c1a25a83e7
Create Date: 2025-03-04 04:12:09.781814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ade5141bc3a7'
down_revision: Union[str, None] = '18c1a25a83e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stems', sa.Column('age_circumference', sa.Integer(), nullable=True))
    op.drop_column('stems', 'age_circumfence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stems', sa.Column('age_circumfence', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stems', 'age_circumference')
    # ### end Alembic commands ###
