"""add_ng_word_reason

Revision ID: d145938be84c
Revises: dd8d53535ee4
Create Date: 2025-03-11 10:07:28.150160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd145938be84c'
down_revision: Union[str, None] = 'dd8d53535ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('censorship_ng_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trees', 'censorship_ng_reason')
    # ### end Alembic commands ###
