"""add_contributor_censorship_status

Revision ID: dd8d53535ee4
Revises: 68077265f9a2
Create Date: 2025-03-11 01:01:40.086309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8d53535ee4'
down_revision: Union[str, None] = '68077265f9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('contributor_censorship_status', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_trees_contributor_censorship_status'), 'trees', ['contributor_censorship_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trees_contributor_censorship_status'), table_name='trees')
    op.drop_column('trees', 'contributor_censorship_status')
    # ### end Alembic commands ###
