"""empty message

Revision ID: e2bb11437e2d
Revises: 15b0bf08dfe1
Create Date: 2025-02-17 12:38:38.966564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bb11437e2d'
down_revision: Union[str, None] = '15b0bf08dfe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stems_age'), 'stems', ['age'], unique=False)
    op.create_index(op.f('ix_trees_vitality'), 'trees', ['vitality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trees_vitality'), table_name='trees')
    op.drop_index(op.f('ix_stems_age'), table_name='stems')
    # ### end Alembic commands ###
