"""add_real_age_to_stem4

Revision ID: faa83b6c8a0b
Revises: dab0a7973397
Create Date: 2025-03-04 04:21:48.265471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa83b6c8a0b'
down_revision: Union[str, None] = 'dab0a7973397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
