"""mysql_float_to_double

Revision ID: ff4a3030df36
Revises: d145938be84c
Create Date: 2025-03-16 00:48:46.577187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff4a3030df36'
down_revision: Union[str, None] = 'd145938be84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entire_trees', 'vitality_real',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_noleaf_real',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_noleaf_weight',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_bloom_real',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_bloom_weight',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('entire_trees', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kobus', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kobus', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('municipality_stats', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('municipality_stats', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('mushrooms', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('mushrooms', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('prefecture_stats', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('prefecture_stats', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('stem_holes', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('stem_holes', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('stems', 'texture_real',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('stems', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('stems', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('tengus', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('tengus', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('trees', 'latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('trees', 'longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trees', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('trees', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('tengus', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('tengus', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('stems', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('stems', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('stems', 'texture_real',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('stem_holes', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('stem_holes', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('prefecture_stats', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('prefecture_stats', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('mushrooms', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('mushrooms', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('municipality_stats', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('municipality_stats', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kobus', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kobus', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('entire_trees', 'longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('entire_trees', 'latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('entire_trees', 'vitality_bloom_weight',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_bloom_real',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_noleaf_weight',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_noleaf_real',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('entire_trees', 'vitality_real',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
